# Generated by Django 5.0 on 2023-12-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='time',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
