# Generated by Django 5.0 on 2023-12-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_price_food_rate_food_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
