# Generated by Django 5.0 on 2023-12-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('appetizers', 'Appetizers'), ('main', 'Main Course'), ('desserts', 'Desserts'), ('drinks', 'Drinks')], default='main', max_length=10),
        ),
    ]
