# Generated by Django 5.0 on 2023-12-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('drinks', 'Drinks'), ('dinner', 'Dinner'), ('lunch', 'Lunch')], default='drinks', max_length=10),
        ),
    ]
